version: "3"
services:
  postgres:
    image: "postgres:11.5"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=123'
    expose:
      - "5433"
    ports:
      - "5433:5433"